[ { dep = "Cabal", ver = "3.12.0.0" }
, { dep = "Cabal-syntax", ver = "3.12.0.0" }
, { dep = "HUnit", ver = "1.6.2.0" }
, { dep = "QuickCheck", ver = "2.15.0.1" }
, { dep = "alex", ver = "3.5.1.0" }
, { dep = "ansi-terminal", ver = "1.0.2" }
, { dep = "ansi-terminal-types", ver = "0.11.5" }
, { dep = "ansi-wl-pprint", ver = "0.6.9" }
, { dep = "async", ver = "2.2.5" }
, { dep = "barbies", ver = "2.1.1.0" }
, { dep = "base-compat", ver = "0.14.0" }
, { dep = "base-orphans", ver = "0.9.2" }
, { dep = "blaze-builder", ver = "0.4.2.3" }
, { dep = "blaze-html", ver = "0.9.2.0" }
, { dep = "blaze-markup", ver = "0.8.3.0" }
, { dep = "boring", ver = "0.2.2" }
, { dep = "cabal-doctest", ver = "1.0.9" }
, { dep = "call-stack", ver = "0.4.0" }
, { dep = "case-insensitive", ver = "1.2.1.0" }
, { dep = "clay", ver = "0.15.0" }
, { dep = "colour", ver = "2.3.6" }
, { dep = "colourista", ver = "0.1.0.2" }
, { dep = "concurrent-output", ver = "1.10.21" }
, { dep = "constraints", ver = "0.14.2" }
, { dep = "cryptohash-sha1", ver = "0.11.101.0" }
, { dep = "dir-traverse", ver = "0.2.3.0" }
, { dep = "distributive", ver = "0.6.2.1" }
, { dep = "dlist", ver = "1.0" }
, { dep = "erf", ver = "2.0.0.0" }
, { dep = "extensions", ver = "0.1.0.2" }
, { dep = "fail", ver = "4.9.0.0" }
, { dep = "gitrev", ver = "1.3.1" }
, { dep = "happy", ver = "1.20.1.1" }
, { dep = "hashable", ver = "1.4.4.0" }
, { dep = "haskell-lexer", ver = "1.1.1" }
, { dep = "hedgehog", ver = "1.4" }
, { dep = "hspec", ver = "2.11.9" }
, { dep = "hspec-core", ver = "2.11.9" }
, { dep = "hspec-discover", ver = "2.11.9" }
, { dep = "hspec-expectations", ver = "0.8.4" }
, { dep = "hspec-hedgehog", ver = "0.1.1.0" }
, { dep = "integer-logarithms", ver = "1.0.3.1" }
, { dep = "lifted-async", ver = "0.10.2.5" }
, { dep = "lifted-base", ver = "0.2.3.12" }
, { dep = "megaparsec", ver = "9.6.1" }
, { dep = "microaeson", ver = "0.1.0.1" }
, { dep = "mmorph", ver = "1.2.0" }
, { dep = "monad-control", ver = "1.0.3.1" }
, { dep = "optparse-applicative", ver = "0.17.1.0" }
, { dep = "parser-combinators", ver = "1.3.0" }
, { dep = "pretty-show", ver = "1.10" }
, { dep = "pretty-simple", ver = "4.1.2.0" }
, { dep = "prettyprinter", ver = "1.7.1" }
, { dep = "prettyprinter-ansi-terminal", ver = "1.1.3" }
, { dep = "primitive", ver = "0.9.0.0" }
, { dep = "quickcheck-io", ver = "0.2.0" }
, { dep = "random", ver = "1.2.1.2" }
, { dep = "relude", ver = "1.2.1.0" }
, { dep = "resourcet", ver = "1.3.0" }
, { dep = "safe-exceptions", ver = "0.1.7.4" }
, { dep = "scientific", ver = "0.3.8.0" }
, { dep = "selective", ver = "0.7.0.1" }
, { dep = "slist", ver = "0.2.1.0" }
, { dep = "splitmix", ver = "0.1.0.5" }
, { dep = "tagged", ver = "0.8.8" }
, { dep = "terminal-size", ver = "0.3.4" }
, { dep = "text-short", ver = "0.1.6" }
, { dep = "tf-random", ver = "0.5" }
, { dep = "tomland", ver = "1.3.3.2" }
, { dep = "transformers-base", ver = "0.4.6" }
, { dep = "transformers-compat", ver = "0.7.2" }
, { dep = "trial", ver = "0.0.0.0" }
, { dep = "trial-optparse-applicative", ver = "0.0.0.0" }
, { dep = "trial-tomland", ver = "0.0.0.0" }
, { dep = "unliftio-core", ver = "0.2.1.0" }
, { dep = "unordered-containers", ver = "0.2.20" }
, { dep = "validation-selective", ver = "0.2.0.0" }
, { dep = "wl-pprint-annotated", ver = "0.1.0.1" }
]
